name: single-image-bg-detector
channels:
  - defaults
dependencies:
  - scikit-image=0.20.0
  - pip:
      - pillow==10.1.0
      - numpy==1.26.1
      - matplotlib==3.8.0
      - ipdb==0.13.13
      - ipython==8.16.1
      - shapely==2.0.2
      - opencv-python==4.8.1.78
