name: single-image-bg-detector
channels:
  - defaults
dependencies:
  - aom=3.6.0
  - blas=1.0
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - cfitsio=3.470
  - charls=2.2.0
  - click=8.0.4
  - cloudpickle=2.2.1
  - cytoolz=0.12.0
  - dask-core=2023.6.0
  - dav1d=1.2.1
  - freetype=2.12.1
  - fsspec=2023.9.2
  - giflib=5.2.1
  - imagecodecs=2023.1.23
  - imageio=2.31.4
  - importlib-metadata=6.0.0
  - jpeg=9e
  - jxrlib=1.1
  - krb5=1.20.1
  - lazy_loader=0.3
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libavif=0.11.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.4.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libssh2=1.10.0
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libzopfli=1.0.3
  - llvm-openmp=14.0.6
  - locket=1.0.0
  - lz4-c=1.9.4
  - ncurses=6.4
  - networkx=3.1
  - numpy-base=1.26.0
  - openjpeg=2.3.0
  - openssl=3.0.11
  - partd=1.4.0
  - pip=23.3
  - python=3.10.13
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - readline=8.2
  - scikit-image=0.20.0
  - scipy=1.11.3
  - setuptools=68.0.0
  - snappy=1.1.9
  - sqlite=3.41.2
  - tifffile=2023.4.12
  - tk=8.6.12
  - toolz=0.12.0
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.4.2
  - yaml=0.2.5
  - zfp=1.0.0
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - appnope==0.1.3
      - asttokens==2.4.0
      - backcall==0.2.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - decorator==5.1.1
      - exceptiongroup==1.1.3
      - executing==2.0.0
      - fonttools==4.43.1
      - ipdb==0.13.13
      - ipython==8.16.1
      - jedi==0.19.1
      - kiwisolver==1.4.5
      - matplotlib==3.8.0
      - matplotlib-inline==0.1.6
      - numpy==1.26.1
      - opencv-python==4.8.1.78
      - packaging==23.2
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.1.0
      - prompt-toolkit==3.0.39
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.16.1
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - shapely==2.0.2
      - six==1.16.0
      - stack-data==0.6.3
      - tomli==2.0.1
      - traitlets==5.11.2
      - wcwidth==0.2.8
